version: "3.9"

services:
  nodeapp1:
    container_name: nodeapp1
    build:
      context: .
      dockerfile: containers/node/Dockerfile
    expose:
      - "8080"

  nodeapp2:
    container_name: nodeapp2
    build:
      context: .
      dockerfile: containers/node/Dockerfile
    expose:
      - "8080"

  ng1:
    container_name: ng1
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    ports:
    - "80:80"

  ng2:
    container_name: ng2
    build:
      context: .
      dockerfile: containers/nginx/Dockerfile
    ports:
    - "81:80"
